spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  ssl:
      key-store:  classpath:keystore.p12
      key-store-password: fanyao
      key-store-type: PKCS12
      key-alias: tomcat
  port: 8433
